---

NODE_ACCESS_WAIT_TIME: 5400
CORTX_ISO_FOLDER: '/opt/isos/' 
SCSI_NETWORK_RELAY_RPM: http://cortx-storage.colo.seagate.com/prvsnr/scsi-network-relay-1.1.0-47.x86_64.rpm
LSI_UTIL: http://cortx-storage.colo.seagate.com/seagate-internal/lsiutil/lsiutil.tar
EXPECT_RPM: http://mirror.centos.org/centos/7/os/x86_64/Packages/expect-5.45-14.el7_1.x86_64.rpm

required_vars:
  - REIMAGE
  - NODE1
  - NODE2
  - CONFIG_URL
  - CORTX_BUILD_ISO_URL
  - CORTX_OS_ISO_URL
  - CORTX_PREP_URL
  - CLUSTER_PASS
  - SATELLITE_UN
  - SATELLITE_PW
  - CHANGE_PASS