STX_PEM: https://raw.githubusercontent.com/Seagate/cortx-prvsnr/pre-cortx-1.0/srv/components/misc_pkgs/ssl_certs/files/stx.pem
S3_IAM_CLI_LOCATION: http://cortx-storage.colo.seagate.com/releases/cortx/github/main/centos-7.8.2003/last_successful/

DATA_DEVICE: /dev/sdb
METADATA_DEVICE: /dev/sdc

REQUIRED_VARS:
  - NODE1
  - CORTX_BUILD

TEST_DATA_OPEN_LDAP_PASS_ROOT: seagate1
TEST_DATA_OPEN_LDAP_PASS_SGIAM: seagate2

