# Reference : https://github.com/Seagate/cortx-s3server/wiki/S3server-provisioning-on-single-node-VM-cluster:-Manual#s3server-mini-provisioning

- name: "[S3server Mini Provisioning] : S3:Post_Install" 
  shell: |
    /opt/seagate/cortx/utils/bin/utils_setup post_install --config "json:///tmp/cortx-config-new"
    /opt/seagate/cortx/s3/bin/s3_setup post_install --config "yaml:///opt/seagate/cortx/s3/conf/s3.post_install.tmpl.1-node"
  register: s3_mini_post_install
  failed_when: '"post_install successful" not in s3_mini_post_install.stdout'

- name: "[S3server Mini Provisioning] : S3:Prepare" 
  shell: |
    /opt/seagate/cortx/utils/bin/utils_setup prepare --config "json:///tmp/cortx-config-new"
    /opt/seagate/cortx/s3/bin/s3_setup prepare --config "yaml:///opt/seagate/cortx/s3/conf/s3.prepare.tmpl.1-node"
  register: s3_mini_prepare
  failed_when: '"prepare successful" not in s3_mini_prepare.stdout'

- name: "[S3server Mini Provisioning] : S3:Config - Start Services" 
  script: files/start_service.sh haproxy slapd rsyslog sshd

- name: "[S3server Mini Provisioning] : S3:Config" 
  shell: |
    /opt/seagate/cortx/utils/bin/utils_setup config --config "json:///tmp/cortx-config-new"
    /opt/seagate/cortx/s3/bin/s3_setup config --config "yaml:///opt/seagate/cortx/s3/conf/s3.config.tmpl.1-node"
  register: s3_mini_config
  failed_when: '"config successful" not in s3_mini_config.stdout'

- name: "[S3server Mini Provisioning] : S3:Init" 
  shell: |
    /opt/seagate/cortx/utils/bin/utils_setup init --config "json:///tmp/cortx-config-new"
    /opt/seagate/cortx/s3/bin/s3_setup init --config "yaml:///opt/seagate/cortx/s3/conf/s3.init.tmpl.1-node"
  register: s3_mini_init
  failed_when: '"init successful" not in s3_mini_init.stdout'
